version: "3"
services:
  jenkins:
    container_name: jenkins-local
    build:
      context: .
      dockerfile: ./Dockerfile
    image: jenkins:local
    environment:
      JENKINS_ADMIN_ID: admin
      JENKINS_ADMIN_PASSWORD: admin
    ports:
      - 9080:8080
      - 50000:50000
